apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blur-rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: blur-rabbitmq
  template:
    metadata:
      labels:
        app: blur-rabbitmq
    spec:
      containers:
      - name: blur-rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_PWD
        - name: RABBITMQ_DEFAULT_VHOST
          valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_VHOST
        ports:
          - containerPort: 5672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate