apiVersion: apps/v1
kind: Deployment
metadata:
  name: blur-service
spec:
  selector:
    matchLabels:
      app: blur
  template:
    metadata:
      labels:
        app: blur
    spec:
      containers:
      - name: blur-service
        image: marjugoncalves/blur-service
        ports:
        - containerPort: 8080
        env:
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_USER
          - name: RABBITMQ_PWD
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_PWD
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_HOST
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_PORT
          - name: RABBITMQ_QUEUE
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: RABBITMQ_QUEUE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: MYSQL_USER 
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: MYSQL_PASSWORD 
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_METADATA_TABLE
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: MYSQL_METADATA_TABLE 
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: AWS_ACCESS_KEY_ID 
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: AWS_REGION 
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: AWS_BUCKET
